cockroachdb/ui

lerna.json, package.json
Adding lerna.json and package.json for future /packages to be added.
=> installing lerna config

packages/ui-components/package-lock.json, packages/ui-components/package.json
- @cockroachlabs/ui-components@0.1.0
=> Publish ui-components v0.1.0

.github/workflows/nodejs.yml, packages/ui-components/package.json
=> let's try a github workflow

packages/storybook-ui-components/.storybook/cockroach-theme.js, packages/storybook-ui-components/.storybook/main.js, packages/storybook-ui-components/.storybook/manager.js, packages/storybook-ui-components/.storybook/preview-head.html, packages/storybook-ui-components/AUTHORS, packages/storybook-ui-components/package-lock.json, packages/storybook-ui-components/package.json, packages/storybook-ui-components/stories/0-Welcome.stories.js, packages/storybook-ui-components/utils/selectKnobMirror.js
This is a pretty minimal setup on which stories can be build on top of.
It creates a simple placeholder theme, installs a few addons, and has a
simple utility for adding sugar to the knobs addon. All to indicate a
direction that may be used as a pattern for future storybook
installations.
This packages is currently unpublished and no consideration has be given to deployment.
=> Storybook setup for UI Components

packages/storybook-ui-components/package-lock.json, packages/storybook-ui-components/package.json
See https://github.com/advisories/GHSA-vh95-rmgr-6w4m
=> Upgrading dependencies to resolve minimist vulnerability

packages/icons/README.md
Some basic info about the `icons` package
=> Icon Package README

.github/pull_request_template.md
Here's a first draft of a pull-request template. I think there's a lot
more to add here as contributing guides get updated.
fixes #34
=> Initial PR Template

packages/icons/package.json, packages/storybook-ui-components/package.json, packages/ui-components/package.json
- @cockroachlabs/icons@0.2.0
- storybook-ui-components@0.1.3
- @cockroachlabs/ui-components@0.1.3
=> Publish icons@0.2.0

packages/icons/package.json, packages/storybook-ui-components/package.json, packages/storybook-ui-components/yarn.lock, packages/ui-components/package.json, packages/ui-components/yarn.lock
- @cockroachlabs/icons@0.2.1
- storybook-ui-components@0.1.4
- @cockroachlabs/ui-components@0.1.4
=> Publish ui-components@0.1.4

packages/design-tokens/tokens/color/background.json, packages/design-tokens/tokens/color/border.json, packages/design-tokens/tokens/color/font.json, packages/design-tokens/tokens/color/shadow.json, packages/storybook-ui-components/stories/Button.stories.tsx, packages/storybook-ui-components/yarn.lock, packages/ui-components/src/Button/Button.module.scss, packages/ui-components/src/Button/Button.test.tsx, packages/ui-components/src/Button/Button.tsx, packages/ui-components/src/Button/README.md, packages/ui-components/src/README.md, packages/ui-components/src/index.ts, packages/ui-components/src/styles/tokens.scss, yarn.lock
* resolves #21 
* implements button component, tests, and story
=> ui-components: Button component

packages/storybook-ui-components/.storybook/main.js, packages/storybook-ui-components/layout/StoryContainer.tsx, packages/storybook-ui-components/layout/StoryDescription.tsx, packages/storybook-ui-components/layout/index.ts, packages/storybook-ui-components/package.json, packages/storybook-ui-components/stories/Avatar.stories.tsx, packages/storybook-ui-components/stories/Badge.stories.tsx, packages/storybook-ui-components/stories/Input.stories.tsx, packages/storybook-ui-components/stories/Tooltip.stories.tsx, packages/storybook-ui-components/yarn.lock
Here are some changes that were prototyped in #74. I'm not sure what happened, but the branch diverged so badly it was easier to start over here.
Adding the [storybook docs addon](https://github.com/storybookjs/storybook/tree/master/addons/docs) and starting to define some layout components for composing repeatable patterns in stories.
This is a start. The next step would be to integrate more README content into our stories as maintaining hand written docs in our repo is something we have decided against.
fixes #46
=> Storybook updates with design

packages/storybook-ui-components/.storybook/preview-head.html, packages/storybook-ui-components/layout/StoryContainer.tsx, packages/storybook-ui-components/stories/Avatar.stories.tsx, packages/storybook-ui-components/stories/Badge.stories.tsx, packages/storybook-ui-components/stories/Button.stories.tsx, packages/storybook-ui-components/stories/Icon.stories.tsx, packages/storybook-ui-components/stories/Tooltip.stories.tsx
Fonts were loading correctly, but were not being applied to stories via the
"cockroach theme" (because that's not how the theme works). I think there
had been an attempt to apply fonts to the stories by using a layout
components, but had incorrectly used OpenSans instead of the correct Source
Sans Pro.
I am correcting the font and applying the layout component to all of the
current stories. There's also a lot of "prettifying" that happened in the
editor.
=> storybook-ui-components // Correcting fonts in stories

CONTRIBUTING.md, packages/ui-components/package.json, packages/ui-components/yarn.lock
Upgrading node-sass to support latest Node version
I'm also adding a section to CONTRIBUTING about troubleshooting errors
that may occur when using Sass to build packages.
=> ui-components // upgrading node-sass

CONTRIBUTING.md
=> ui-components: update README with guidance re: class name prefixing

.github/workflows/deploy-storybook.yml, .github/workflows/publish-ui-components.yml, .github/workflows/pull-request-ci.yml, packages/ui-components/package.json
Trying to work out some issues with our Github actions
=> Debugging Github Workflows

package.json, packages/storybook-ui-components/package.json, packages/storybook-ui-components/yarn.lock, packages/ui-components/src/Badge/Badge.module.scss, packages/ui-components/yarn.lock, yarn.lock
Updating all the underlying dev dependencies with `yarn
upgrade-interactive` and also making sure we are on the latest version
of our own interlinked dependencies.
=> Dependency updates

packages/storybook-ui-components/package.json, packages/storybook-ui-components/yarn.lock
Adding resolution for prismjs@1.21.0 to resolve https://github.com/advisories/GHSA-wvhm-4hhf-97x9
=> Adding resolution for prismjs

packages/storybook-ui-components/stories/Icon.stories.tsx, packages/storybook-ui-components/stories/InlineAlert.stories.tsx, packages/ui-components/src/Icon/Icon.module.scss, packages/ui-components/src/Icon/Icon.test.tsx, packages/ui-components/src/Icon/Icon.tsx, packages/ui-components/src/InlineAlert/InlineAlert.module.scss, packages/ui-components/src/InlineAlert/InlineAlert.test.tsx, packages/ui-components/src/InlineAlert/InlineAlert.tsx, packages/ui-components/src/InlineAlert/__snapshots__/InlineAlert.test.tsx.snap, packages/ui-components/src/index.ts
InlineAlert component is one of basic components in Design System to
provide users with feedback on a page. It doesn't disappear and has
to be placed somewhere on a page.
=> InlineAlert component

packages/storybook-ui-components/stories/Button.stories.tsx, packages/ui-components/src/Button/Button.module.scss, packages/ui-components/src/Button/Button.test.tsx, packages/ui-components/src/Button/Button.tsx, packages/ui-components/src/Button/README.md
This PR is a collection of changes required to integrate the component into the CockroachCloud console application.
fixes #123
=> ui-components: Button integration tweaks

packages/ui-components/package.json
Adding to ui-components, as I don't think we need it in any other package.
Added as a dev dependency.
=> ui: Add react-final-form as devdependency

packages/storybook-ui-components/stories/Icon.stories.tsx
Got a little too aggressive in changing the width of `IconDisplay`
=> Icon Stories Visual Bug

packages/storybook-ui-components/yarn.lock
Updating yarn.lock file to pick up latest ui-component changes.
=> storybook-ui-components: Upgrade ui-components

CODEOWNERS
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/ui/168)
=> set CODEOWNERS on admin-ui-components

packages/design-tokens/tokens/color/base.json, packages/design-tokens/tokens/color/intent.json, packages/design-tokens/tokens/component/avatar.json, packages/design-tokens/tokens/component/badge.json, packages/design-tokens/tokens/component/button.json, packages/design-tokens/tokens/component/inline-alert.json, packages/storybook-ui-components/stories/InlineAlert.stories.tsx, packages/ui-components/src/Avatar/Avatar.module.scss, packages/ui-components/src/InlineAlert/InlineAlert.module.scss, packages/ui-components/src/InlineAlert/InlineAlert.test.tsx, packages/ui-components/src/InlineAlert/InlineAlert.tsx, packages/ui-components/src/InlineAlert/__snapshots__/InlineAlert.test.tsx.snap
=> Intent Tokens to support Inline Alerts

packages/cluster-ui/package.json, packages/design-tokens/package.json, packages/storybook-ui-components/package.json, packages/ui-components/package.json
Publishing is currently failing due to svgr error about cosmis config
=> Sync'ing manually published versions

docs/buttons.md
=> Added copy for the buttons doc

docs/assets/Assets folder
=> Create Assets folder

packages/cluster-ui/README.md
This is meant to help CRDB devs get up to speed
on how to work with this repository.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/ui/199)
=> cluster-ui: update README to summarize dev workflow

packages/cluster-ui/src/util/appStats.ts
additional null check to fix crashes in dbconsole envoirement
=> cluster-ui: fix appstat utils

CODEOWNERS
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/ui/221)
=> CODEOWNERS: replace individuals with cluster-ui-prs

packages/cluster-ui/jest.testing.config.js, packages/cluster-ui/package.json, packages/cluster-ui/src/multiSelectCheckbox/multiSelectCheckbox.module.scss, packages/cluster-ui/src/multiSelectCheckbox/multiSelectCheckbox.tsx, packages/cluster-ui/src/queryFilter/filter.module.scss, packages/cluster-ui/src/queryFilter/filter.tsx, packages/cluster-ui/src/queryFilter/filterClasses.ts, packages/cluster-ui/src/statementsPage/statementsPage.fixture.ts, packages/cluster-ui/src/statementsPage/statementsPage.tsx, packages/cluster-ui/src/util/appStats/appStats.spec.ts, packages/cluster-ui/src/util/appStats/appStats.ts, yarn.lock
Cluster-ui
- Update of `react-select` from version `1.2.1` to `4.3.0`  and `@types/react-select` from version `1.2.6` to `4.0.14` and changes to fix compatibility with the new version
- Creation of new multi select component
- New filter on Statements Page for SQL Type (DDL, DML, DCL and TCL)
Resolves: https://github.com/cockroachdb/cockroach/issues/49178
=> cluster-ui: sql type filter

packages/cluster-ui/src/sessions/sessionsPage.tsx, packages/cluster-ui/src/sessions/sessionsPageConnected.tsx, packages/cluster-ui/src/sessions/sessionsTable.tsx
fix sessions table sort event payload
=> cluster-ui: sessions tracking

packages/ui-components/src/Tooltip/Tooltip.module.scss
style changes for tooltip component to avoid css conflicts in
managed service environment.
=> ui-components: tooltip component updates

packages/cluster-ui/package.json, yarn.lock
update ui-components dep that contain latest tooltip fixes
=> cluster-ui: bump ui-components

packages/cluster-ui/src/transactionDetails/transactionDetails.fixture.ts, packages/cluster-ui/src/transactionDetails/transactionDetails.stories.tsx, packages/cluster-ui/src/transactionDetails/transactionDetails.tsx, packages/cluster-ui/src/transactionsPage/transactions.fixture.ts, packages/cluster-ui/src/transactionsPage/transactionsPage.stories.tsx, packages/cluster-ui/src/transactionsPage/transactionsPage.tsx
Part of issue cockroachdb/cockroach#64779
This will be followed by another PR with the changes on the ui visible to the user.
=> cluster-ui: returning information about which region each node is on

renovate.json5
Add additional configuration to `renovate.json5` mirroring much of what has been implemented in the managed service repo.
=> Add renovate.json5

renovate.json
Previous work did not properly remove `renovate.json`.
=> Delete renovate.json in favor of renovate.json5

packages/ui-components/src/Tooltip/Tooltip.tsx
adjust event listener, to capture all possible scroll
events.
=> ui-components: hide tooltip on scroll

packages/design-tokens/tokens/color/metrics.json
Adding metrics color tokens defined in Figma
=> # design-tokens // Adding metrics colors for use in graphs

packages/design-tokens/tokens/color/metrics.json
Based on feedback from design updating metrics colors for readability
=> tokens: Updating metrics colors

packages/ui-components/src/index.ts
This commit exports the ExpandableText component in the ui-components package.
- N/A I have written or updated test for the changes I made
- N/A I have updated the README of the package I'm working in to reflect my changes
- N/A I have added or updated Storybook if appropriate for my changes
=> ui-components: Export the ExpandableText component

packages/storybook-ui-components/stories/Charts.stories.tsx, packages/ui-components/package.json, packages/ui-components/src/Charts/README.md, packages/ui-components/src/Charts/barChart.module.scss, packages/ui-components/src/Charts/barChart.tsx, packages/ui-components/src/Charts/helpers.ts, packages/ui-components/src/index.ts, yarn.lock
Currently `uPlot` is the graphing library of choice for timeseries data
across Cockroach Labs. This libraries is heavilily optimized to high
volume timeseries data, which it does great at! `uPlot` can effectively
render tens of thousands of points in a very quick timeframe.
Unfortunately! `uPlot`'s support for plugins leaves a fair bit to be
desired in terms of flexibility in visualizing categorical data. To aid
this, this PR proposes using `Recharts` with a wrapper for defining a
similarly styled graph. The first component introduced is a normal
`BarChart` component, which provides a few options for fitting an
internal use case that we have. Additional features can easily be added
through updating this component in the `ui` library.
This components functionality and a small use case is …
=> ui-components: add recharts and bar chart component

lerna.json, packages/design-tokens/tokens/component/button.json, packages/storybook-ui-components/package.json, packages/storybook-ui-components/stories/Button.stories.tsx, packages/ui-components/package.json, packages/ui-components/src/Button/Button.module.scss, packages/ui-components/src/Button/Button.test.tsx, packages/ui-components/src/Button/Button.tsx, packages/ui-components/webpack.config.js, yarn.lock
=> ui-components: Add link-style to button

.github/workflows/release.yml, packages/icons/package.json
Adding a build step to `Release` workflow. It seems `lerna` doesn't have the ability to be able to tell when to build local dependencies when a package is being published.
For example, [this build](https://github.com/cockroachdb/ui/actions/runs/3267342199/jobs/5372386174) completes successfully because every package was built in order to create a canary release. Whereas [this build](https://github.com/cockroachdb/ui/actions/runs/3267333237/jobs/5372364824) fails because only two packages are being published (`design-tokens` and `ui-components`) and `ui-components` depends on `icons`.
```
Found 2 packages to publish:
- @cockroachlabs/design-tokens => 0.4.10
- @cockroachlabs/ui-components => 0.3.11
....
> @cockroachlabs/ui-components@0.3.11 build:typescript
> tsc
Error: …
```
=> adding lerna build to release workflow

packages/ui-components/src/Icon/CreditCard.tsx, packages/ui-components/src/Icon/Flag.tsx, packages/ui-components/src/Icon/Illustration.tsx, packages/ui-components/src/Icon/Pictogram.module.scss, packages/ui-components/src/Icon/Pictogram.tsx, packages/ui-components/src/Icon/ThirdPartyIcon.module.scss, packages/ui-components/src/Icon/ThirdPartyIcon.tsx, packages/ui-components/src/Icon/card.module.scss
- ui-components: Remove margin: auto from icon components
- ui-components: export proptypes from icon components
<details>
<br />
```bash
npm install @cockroachlabs/ui-components@0.7.6-canary.525.5391955760.0
yarn add @cockroachlabs/ui-components@0.7.6-canary.525.5391955760.0
```
</details>
=> icon adjustments

README.md, packages/storybook-ui-components/.storybook/preview.ts, packages/storybook-ui-components/stories/ExpandableText.stories.tsx, packages/storybook-ui-components/stories/Input.stories.tsx
- update import of main styles to use in storybook;
- update components with required types in stories;
Resolves: https://cockroachlabs.atlassian.net/browse/CC-27874
=> storybook: fix imports and required types
