cockroachdb/ui

- packages/ui-components/src/utils/README.md
- packages/ui-components/src/utils/objectToClassnames.test.ts
- packages/ui-components/src/utils/objectToClassnames.ts
Due to the fact that we are using the bind version of classnames
(https://github.com/JedWatson/classnames#alternate-bind-version-for-css-modules)
a array of strings is required rather than a concatinated string of
classnames.
> Changing objectToClassnames to return array

- packages/eslint-config/package.json
In order to publish scoped packages, access must be set to public.
See https://github.com/lerna/lerna/tree/master/commands/publish#per-package-configuration for more details.
> Add publishConfig so publishing scoped packages doesn't fail

- packages/eslint-config/index.js
Allow `() => {}` which is commonly used in tests.
I think this behavior changed in:
https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/CHANGELOG.md#2100-2019-12-02
Fixes: https://teamcity.cockroachdb.com/buildConfiguration/Internal_ManagedService_GitHubCiLint/1760914?buildTab=log&focusLine=3&linesState=352
> Override ts lint rule to allow empty arrow functions

- packages/eslint-config/yarn.lock
Upgrading `eslint` to resolve vulnerability in `minimist@0.2.0` (see
https://github.com/advisories/GHSA-vh95-rmgr-6w4m)
```
@cockroachlabs/eslint-config@0.1.2 /Users/nathanstilwell/Code/ui/packages/eslint-config
└─┬ eslint@6.8.0
└─┬ mkdirp@0.5.5
└── minimist@1.2.5
```
> Resolution for minimist vulnerability

- README.md
- package.json
- packages/icons/package.json
- packages/storybook-ui-components/package.json
- packages/ui-components/package.json
- packages/ui-components/webpack.config.js
Provided 2 new npm scripts on top level:
`npm run init` - will install all node modules and run needed lerna commands for local setup
`npm start` - will start start `watch` dev servers for all packages inside one terminal window. no need to cd manually and having multiple terminals.
> added npm scripts to simplify local setup and running dev servers

- .github/workflows/pull-request-ci.yml
I'm renaming the action to be a little more descriptive and adding more
steps with names to make this action a little easier to see what's going
on.
I have added a step to build each package after bootstrap. This will
prevent errors where a package is linked, but the dist/ folder may not
exist and so the package will appear to not exist or not be installed
correctly.
> Adjusting PR github action

- packages/storybook-ui-components/stories/2-Avatar.stories.tsx
- packages/ui-components/src/Avatar/Avatar.module.scss
- packages/ui-components/src/Avatar/Avatar.test.tsx
- packages/ui-components/src/Avatar/Avatar.tsx
- packages/ui-components/src/Avatar/README.md
- packages/ui-components/src/Avatar/index.ts
- packages/ui-components/src/index.js
Issue #22
- Includes base implementation of <Avatar> component which includes
the ability to modify intent, size, disable, and set selectable props
to component.
- It is a starting point to extend this implementation for more
custom representations as StepAvatar and Validation which require
customization of styles.
- Storybook is updated with one more story to show <Avatar> component in different
states, it is a draft version to validate current implementation only.
> ui-components: Avatar

- .github/workflows/deploy-storybook.yml
Preventing storybook deploy action from running  on forks (which don't have
access to secrets) by adding a condition to the deploy action to only
match on [repository owner](https://help.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#github-context) "cockroachdb".
> Debugging storybook deploy

- package.json
I had previously used `--no-lockfile` thinking that it would install but
not generate a new lockfile, but the correct switch for that behavior is
`--pure-lockfile`. This switch will read from the lockfile without
generating updates.
> Incorrect yarn install switch

- .github/workflows/publish-ui-components.yml
Publishing to NPM registry is a multistep action with the following steps:
- run tests to ensure build is healthy;
- bump package with a new version, it creates a new commit in "master" branch and a tag for the new version
- push these changes (in "master" branch and tag)
- and finally publish to NPM
This action requires NPM Access Token to publish packages.
Token has to be set in secrets as YARN_TOKEN.
Note:
- extra commit is pushed to "master" branch in order to increment the version.
- commit is created under user name (who initiated this action) and with
empty ("<>") email because action context doesn't provide such information.
> ui-components: Publish to NPM registry with Github actions

- packages/storybook-ui-components/stories/Badge.stories.tsx
- packages/ui-components/src/Badge/Badge.module.scss
- packages/ui-components/src/Badge/Badge.test.tsx
- packages/ui-components/src/Badge/Badge.tsx
Adding a "blue" intent called "info" to Badge component
fixes #110
Also in this PR,
- Adjusting padding to match mocks
- Extending `BadgeProps` with `HTMLDivElement` attributes. This is immediately for the purpose of adding a `className` prop to Badge during implementation.
> ui-components // Adding info intent to Badge

- packages/storybook-ui-components/layout/Label.tsx
- packages/storybook-ui-components/layout/Sample.tsx
- packages/storybook-ui-components/layout/index.ts
- packages/storybook-ui-components/stories/FuzzyTime.stories.tsx
- packages/ui-components/src/FuzzyTime/FuzzyTime.module.scss
- packages/ui-components/src/FuzzyTime/FuzzyTime.test.ts
- packages/ui-components/src/FuzzyTime/FuzzyTime.tsx
- packages/ui-components/src/FuzzyTime/constants.ts
- packages/ui-components/src/FuzzyTime/util.ts
- packages/ui-components/src/FuzzyTime/utils.test.ts
- packages/ui-components/src/index.ts
For the Notifications work being done by the Observability team, I needed to render _fuzzy times_ given timestamps (something like _"5 sec ago", "10 min ago"_,  etc). I felt like this is something we are likely to see again in designs and so I'm skipping ahead and adding it here.
> ui-components // FuzzyTime Component

- packages/storybook-ui-components/stories/Avatar.stories.tsx
- packages/ui-components/src/Avatar/Avatar.module.scss
- packages/ui-components/src/Avatar/Avatar.test.tsx
- packages/ui-components/src/Avatar/Avatar.tsx
I am extending the props from Avatar with attributes from HTMLDivElement.
This patten has been used in other components is necessary to extend
Avatar for integration with CockroachCloud console. I have also updated
the Avatar stories to demonstrate the use cases.
fixes #112
> ui-components: Extending Avatar props

- packages/ui-components/src/FuzzyTime/FuzzyTime.tsx
- packages/ui-components/src/FuzzyTime/util.ts
Passing through any props recieved for the underlying span element
rendered by FuzzyTime
> Extending FuzzyTime props with native span props

- packages/design-tokens/README.md
- packages/design-tokens/config.json
- packages/design-tokens/package.json
Generating a tokens.d.ts file for TypeScript support in applications. It
turns out that TypeScipt can infer types from exports that have
primative types, so we are just generating a duplicate of tokens.js with
a `.d.ts` extension and identifying it as `types` in package.json.
fixes #109
~I have updated the README of the package I'm working in to reflect my changes~
~I have added or updated Storybook if appropriate for my changes~
> # Design Tokens // Adding types for design tokens

- packages/storybook-ui-components/stories/Spinner.stories.tsx
- packages/ui-components/src/Spinner/Spinner.module.scss
- packages/ui-components/src/Spinner/Spinner.test.tsx
- packages/ui-components/src/Spinner/Spinner.tsx
- packages/ui-components/src/Spinner/__snapshots__/Spinner.test.tsx.snap
- packages/ui-components/src/index.ts
Spinner component is animated loading indicator which can be
used in tables or on pages and indicate intermediate state.
This component doesn't reuse existing Spinner icon due to
technical limitations. Loading icon is rendered with `<path>`
element which is difficult to animate and make it rotate around
SVG central point. That's why current component implements its
own loading icon based on `<circle>` element.
For comparison, loading indicator which is used in Admin UI right now:
> ui-components: Spinner component

- packages/storybook-ui-components/stories/Icon.stories.tsx
- packages/ui-components/src/Icon/Icon.module.scss
- packages/ui-components/src/Icon/Icon.test.tsx
- packages/ui-components/src/Icon/Icon.tsx
- packages/ui-components/src/Icon/__snapshots__/Icon.test.tsx.snap
- packages/ui-components/src/InlineAlert/InlineAlert.test.tsx
- packages/ui-components/src/InlineAlert/InlineAlert.tsx
- packages/ui-components/src/InlineAlert/__snapshots__/InlineAlert.test.tsx.snap
Tint is not used, replaced with intent, inline styling added for container incase container styling is needed (if Icon is more widely used in console, it will need container styling. Currently for being used in ui-component, in NewPasswordInput, we don't need container styling).
> ui: refactor icon component to use in Input components

- packages/storybook-ui-components/yarn.lock
For whatever reason, the Storybook was pointing at a outdated version of `ui-components` as a dependency, but had changed the API for button components rendering buttons without intent props. This PR updates the `yarn.lock` file to ensure the latest version on `ui-components` is deployed. In the process, the integrity SHA for almost every dependency changed, making the file essentially unreviewable.
> upgrading ui-components version

- packages/ui-components/src/Icon/Illustration.module.scss
Adding height 100% for illustrations to fill their containers up to a
maximum specified by the design system.
> ui-components: Illustration flexible height

- .github/workflows/publish-admin-ui-components.yml
- .github/workflows/publish-ui-components.yml
This reverts commit 228e029397e02ef8801b6ab10badc148365f765d.
Our `package.json` files aren't ready for this change yet.
> Revert "use --production flag with yarn on publish actions"

- packages/admin-ui-components/.yarnrc
Necessary for clarity and to trigger the publish
step in the package.
> Add version tag prefix for admin-ui-components

- packages/admin-ui-components/package.json
- packages/admin-ui-components/src/api/basePath.ts
- packages/admin-ui-components/src/api/fetchData.ts
- packages/admin-ui-components/src/api/index.ts
- packages/admin-ui-components/src/api/statementsApi.ts
- packages/admin-ui-components/src/index.ts
- packages/admin-ui-components/src/store/sagas.ts
- packages/admin-ui-components/src/store/statements/statements.sagas.spec.ts
- packages/admin-ui-components/src/store/statements/statements.sagas.ts
- yarn.lock
Ported from PR https://github.com/cockroachdb/admin-ui-components/pull/48
With new requirements, base path for api calls can be arbitrary and
might not rely on browser's path or whatever.
This change implements getter/setter functions to directly set
base path which is needed to use for api requests.
Also it simplifies and eliminates passing basePath as extra
argument through sagas.
> db-console: directly set base path for API requests

- packages/admin-ui-components/.storybook/decorators/index.ts
- packages/admin-ui-components/.storybook/decorators/withBackground.tsx
- packages/admin-ui-components/.storybook/decorators/withRouterProvider.tsx
- packages/admin-ui-components/src/dropdown/dropdown.module.scss
- packages/admin-ui-components/src/dropdown/dropdown.tsx
- packages/admin-ui-components/src/index.ts
- packages/admin-ui-components/src/sessions/index.ts
- packages/admin-ui-components/src/sessions/sessionDetails.module.scss
- packages/admin-ui-components/src/sessions/sessionDetails.tsx
- packages/admin-ui-components/src/sessions/sessionDetailsPage.fixture.ts
- packages/admin-ui-components/src/sessions/sessionDetailsPage.stories.tsx
- packages/admin-ui-components/src/sessions/sessionsPage.fixture.ts
- packages/admin-ui-components/src/sessions/sessionsPage.module.scss
- packages/admin-ui-components/src/sessions/sessionsPage.stories.tsx
- packages/admin-ui-components/src/sessions/sessionsPage.tsx
- packages/admin-ui-components/src/sessions/sessionsTable.module.scss
- packages/admin-ui-components/src/sessions/sessionsTable.tsx
- packages/admin-ui-components/src/sessions/sessionsTableContent.tsx
- packages/admin-ui-components/src/sessions/terminateQueryModal.tsx
- packages/admin-ui-components/src/sessions/terminateSessionModal.tsx
- packages/admin-ui-components/src/statementsTable/statementsTableContent.tsx
- packages/admin-ui-components/src/summaryCard/index.tsx
- packages/admin-ui-components/src/summaryCard/styles.scss
- packages/admin-ui-components/src/summaryCard/summaryCard.module.scss
- packages/admin-ui-components/src/tooltip2/tooltip.tsx
- packages/admin-ui-components/src/util/constants.ts
- packages/admin-ui-components/src/util/docs.ts
ui: Extract Sessions Page from DB Console
extract session page into ui repo:
- most of the components moved without any or minimal changes
- styles converted to scss modules
Resolves: #57296
Release note (ui): none
> ui: Extract Sessions Page from DB Console

- packages/admin-ui-components/src/sessions/sessionsTableContent.tsx
This change updates the sessions page to use
'duration' instead of 'age' and 'transaction'
instead of 'txn'. This aims to make the meaning
of these fields less ambiguous.
Release note (ui change): On the sessions page in db console, any 'age'
label has been replaced with 'duration' and 'txn' has been replaced with
'transaction'. This was only a label change, with the actual metrics
remaining unchanged.
Relates to cockroachdb/cockroach#57047.
> admin-ui-components: sessions page copy changes

- packages/admin-ui-components/package.json
Initially, path to declaration file was wrong and didn't
allow to properly provide type definitions in client apps
which imported `admin-ui-components`.
Changed to reflect correct path where index.d.ts file is
generated during build.
> db-console: fix path for bundled declarations file

- packages/admin-ui-components/.npmignore
- packages/admin-ui-components/package.json
- packages/admin-ui-components/tsconfig.json
Previous tsconfig.json configuration didn't exclude files files
for test configurations and storybooks and somehow it caused
strange behavior when source typings weren't included in final
package.
This change explicitly excludes any top level config files and
storybooks in ./src to prevent typescript from generating any
typings for those files.
It doesn't affect test execution and storybooks.
Excluded files from `.npmignore` is just clean up to avoid
non-production files to be included in package.
> db-console: tsconfig to generate typings for source files only

- packages/cluster-ui/package.json
- packages/cluster-ui/webpack.config.js
Initially, webpack config was defined with hard coded "development"
mode that isn't sufficient for production.
Now, webpack's "mode" option is provided as an argument in package.json
to set production mode for builds.
Production mode provides a set of optimizations to minify bundle
> db-console: optimize Webpack build process with production mode

- packages/cluster-ui/babel.config.js
- packages/cluster-ui/package.json
- packages/cluster-ui/src/declaration.d.ts
- packages/cluster-ui/src/index.ts
- packages/cluster-ui/src/modal/modal.tsx
- packages/cluster-ui/src/pagination/pagination.tsx
- packages/cluster-ui/src/search/search.tsx
- packages/cluster-ui/src/sortedtable/tableSpinner/tableSpinner.tsx
- packages/cluster-ui/src/sql/highlight.tsx
- packages/cluster-ui/src/table/table.tsx
- packages/cluster-ui/src/tooltip/tooltip.tsx
- packages/cluster-ui/src/tooltip2/tooltip.tsx
- packages/cluster-ui/src/transactionsPage/filter/filter.tsx
- packages/cluster-ui/webpack.config.js
- yarn.lock
There is five dependencies that mostly impacted the size of bundle: `crdb-protobuf-client`, `moment.js`, `lodash`, `highlight.js`, and `antd`.
- Moment.js by default imported all locales;
- highlight.js imported syntax configs for different languages (only SQL syntax is used)
- antd imported many unused components and styles.
Current changes handle these three libs (except `lodash`) with limiting imports to required functionalities.
It is easier to review this PR per commit with more detailed explanation in commit messages.
Current changes reduce the size of bundle from ~20Mb to ~14Mb
PS: `lodash` imports aren't optimized here because they require code changes (eliminate `_.chain` usage)
PS: `crdb-protobuf-client` size is ~6Mb from total size (50%) not minified. Require optimizations …
> cluster-ui: optimize bundle size

- .github/workflows/publish-cluster-ui.yml
- renamed publish yml file to reflect new package name
- fixed name of final publish action to reflect correct package name
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/ui/175)
> fix naming in cluster-ui publish action

- packages/cluster-ui/src/statementsPage/statementsPage.selectors.ts
- packages/cluster-ui/src/store/statementDiagnostics/statementDiagnostics.sagas.spec.ts
- packages/cluster-ui/src/store/statementDiagnostics/statementDiagnostics.selectors.spec.ts
- packages/cluster-ui/src/store/statementDiagnostics/statementDiagnostics.selectors.ts
Due to missed type definition for returned type for
`selectDiagnosticsReportsPerStatement` selector, it caused
a regression issue when instead of returning the list of all
diagnostics reports per statement, this selector returned only last report
(according to previous and outdated requirements).
Now, return type is explicitly defined for `selectDiagnosticsReportsPerStatement`
selector and it returns aggregated statement stats with all diagnostics reports
per statement.
We need all reports on Statements page to show dropdown list with current state
for recently requested diagnostics and links for previously generated reports.
Before:
After:
> cluster-ui: provide ordered list of diagnostics to statements page

- packages/cluster-ui/src/core/index.module.scss
- packages/cluster-ui/src/core/typography.module.scss
- packages/cluster-ui/src/dropdown/dropdown.tsx
- packages/cluster-ui/src/sessions/sessionsTable.module.scss
- packages/cluster-ui/src/sortedtable/table.module.scss
- packages/cluster-ui/src/statementsPage/statementsPage.module.scss
- packages/cluster-ui/src/statementsPage/statementsPage.tsx
- packages/cluster-ui/src/statementsTable/statementsTable.module.scss
- packages/cluster-ui/src/statementsTable/statementsTableContent.module.scss
- packages/cluster-ui/src/transactionsTable/transactionsCells/transactionsCells.module.scss
In this PR I'm truncating long queries in several places where they are displayed in tabular form through DB Console. There are a couple of CSS techniques that come into play (see commit messages and / or code for details) and there was not uniform place to make a unifying change. 
**Statements**
**Statements Application Filter**
**Transactions**
**Sessions**
> # cluster-ui // Truncating long queries with CSS

- packages/cluster-ui/package.json
- packages/cluster-ui/src/barCharts/barCharts.module.scss
- packages/cluster-ui/src/barCharts/barCharts.stories.tsx
- packages/cluster-ui/src/barCharts/barCharts.tsx
- packages/cluster-ui/src/statementDetails/statementDetails.fixture.ts
- packages/cluster-ui/src/statementsPage/statementsPage.fixture.ts
- packages/cluster-ui/src/statementsTable/statementsTable.module.scss
- packages/cluster-ui/src/statementsTable/statementsTable.tsx
- packages/cluster-ui/src/statementsTable/statementsTableContent.tsx
- yarn.lock
This commit adds columns for execution stats that we want to display for 21.1.
Namely, this adds rows/bytes read, max memory, and network bytes sent. The
rows affected column has been removed.
The commit also reorders all column-related code to follow the graphical order.
Here is what that looks like with some example queries run against tpch:
Closes https://github.com/cockroachdb/cockroach/issues/59294
Please let me know which tests to update and how. I have run into some issues with "accessing property mean of undefined" which is most likely due to unset proto fields. Is that something I need to handle in the protojs package in cockroach? If not, I'd appreciate if someone could point me to how to write tests for this and other cases.
I'm explicitly not adding code to handle cases when …
> cluster-ui: update statements page

- CODEOWNERS
We have decided to provide some documentation around usage and patterns for components and assets in the UI Repo. Being a design focused subject, I am adding our product designers as reviewers for this documentation.
> Add Designers as Docs reviewers

- packages/cluster-ui/src/statementsTable/statementsTableContent.tsx
Before, cluster-ui base path was defined as '/' root path and
links relied on it. But now, base pack can be set to any other
path and all requests on server should append updated base path.
`getBasePath` function returns current base path or empty string
if it is not set.
This change updates the link to use `getBasePath` and build
valid URL which includes base path.
> cluster-ui: fix link on statement diagnostics bundle

- packages/cluster-ui/package.json
- packages/cluster-ui/src/barCharts/barCharts.tsx
- packages/cluster-ui/src/statementsTable/statementsTableContent.tsx
- packages/cluster-ui/src/transactionsPage/utils.ts
- packages/cluster-ui/src/transactionsTable/transactionsBarCharts.ts
- packages/cluster-ui/src/transactionsTable/transactionsTable.tsx
- packages/cluster-ui/src/transactionsTable/transactionsTableClasses.ts
- packages/cluster-ui/src/util/appStats.spec.ts
- packages/cluster-ui/src/util/appStats.ts
This PR has https://github.com/cockroachdb/cockroach/pull/59761 as a dependency. I'll just wait for that to go in before updating with the new protobuf version number.
This PR, similarly to #178, changes the transactions page to what we've designed for 21.1 (@Annebirzin). This is the result:
cc @awoods187 
Closes https://github.com/cockroachdb/cockroach/issues/59295
> cluster-ui: update transactions page with execution stats

- packages/icons/package.json
- yarn.lock
svgr fails to build icons with 5.4.0 and 5.5.0 versions,
probably due to regression issue (reported and not fixed
yet https://github.com/gregberge/svgr/issues/449)
svgr-cli is downgraded to latest working version 5.3.0
> icons: downgrade @svgr/cli to 5.3.0 version

- .github/workflows/publish-cluster-ui.yml
- packages/cluster-ui/package.json
Latest changes to cluster-ui introduced incompatibility
between CRDB version 20.2 and ongoing development for 21.1.
Changes related to CockroachDb 21.x versions have to be
added to 0.2.x version and 0.1.x version will be targeted
to CockroachDb 20.2 version (for hotfixes, etc)
cluster-ui@0.1.x ver can be published from `cluster-ui-20.2`
branch.
> cluster-ui: bump cluster-ui to 0.2.x version

- .github/workflows/publish-cluster-ui.yml
- packages/cluster-ui/package.json
cluster-ui-20.2 branch has to maintain the changes for 0.1.x version,
but it was not branched out from the latest version and now its version
has to be updated manually.
```
master     |---- 0.1.46 ---- 0.1.51 --- 0.2.x --->
cluster-ui-20.2     \---- 0.1.52 ---->
```
`master` branch includes 0.1.51 version - latest 0.1.x version on
that branch, and then the minor version incremented to 0.2.x
Depends on: https://github.com/cockroachdb/ui/pull/210
> cluster-ui: bump to the latest 0.1.x version in cluster-ui-20.2 branch

- packages/cluster-ui/babel.config.js
- packages/cluster-ui/package.json
- yarn.lock
Before, when components from `cluster-ui` packages were dynamically imported
into client code, it might fail to load with an error "regeneratorRuntime is
not defined" error that explained in following `babel` issue
https://github.com/babel/babel/issues/8829.
As a solution, `babel-runtime` and `@babel/plugin-transform-runtime` plugin are
added in package.
> cluster-ui: add babel-runtime to support dynamic loading

- packages/cluster-ui/src/sql/box.tsx
- packages/cluster-ui/src/transactionDetails/transactionDetails.modules.scss
- packages/cluster-ui/src/transactionDetails/transactionDetails.tsx
- packages/cluster-ui/src/transactionsPage/transactionsPage.tsx
- packages/cluster-ui/src/transactionsTable/transactionsCells/transactionsCells.tsx
- packages/cluster-ui/src/transactionsTable/transactionsTable.tsx
This PR implements the design of the transaction overview page. I modified some things from the original design and got to:
@Annebirzin / @awoods187 I'd like an answer specifically to:
I also left a TODO to add temporary disk max usage, which requires a change on the backend.
Some CSS issues I need help with from @dhartunian or someone on the CC observability team:
Closes https://github.com/cockroachdb/cockroach/issues/59297
> cluster-ui: update transaction overview page with execution stats

- packages/cluster-ui/src/statementDetails/statementDetails.module.scss
- packages/cluster-ui/src/statementDetails/statementDetails.tsx
Closes https://github.com/cockroachdb/cockroach/issues/59296
First commit is #197 so please only review the second one. That PR should go in before this. This PR updates the statement details page with currently available execution stats. This looks like:
I followed the `Heading/Text` pattern for all labels/values. I do need some CSS help to:
@Annebirzin some notes:
- The design gets rid of the distributed execution label. This SGTM but just want to double check it's intentional.
- We can't add the "Executed as follower read" and "Estimated network round trips" because we don't have that data. We could add the *actual* round trips with a bit of plumbing in another pass if that's something we'd like to show.
- I was about to write network bytes is repeated, but we've already touched upon …
> cluster-ui: add execution stats to statement details page

- .github/workflows/publish-cluster-ui.yml
This action allows the manual triggering of the GitHub action from the
GitHub UI. Useful to retrigger builds from master.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/ui/224)
> cluster-ui: add workflow_dispatch to pub action

- .github/workflows/deploy-storybook.yml
- README.md
- package.json
- packages/storybook-ui-components/package.json
- yarn.lock
`storybook-ui-components` package always depends on the latest
version of `ui-components` package and during development Storybook
has to apply all local changes.
To achieve this, `storybook-ui-components` installs `ui-components`
package as a linked dependency so it always has latest version.
Before, it relied on "next" tag that didn't work as expected and
it was a reason when local installs failed.
> storybook: link ui-components dependencies

- packages/cluster-ui/package.json
- packages/cluster-ui/src/barCharts/barCharts.tsx
- packages/cluster-ui/src/statementDetails/statementDetails.fixture.ts
- packages/cluster-ui/src/statementDetails/statementDetails.tsx
- packages/cluster-ui/src/statementsPage/statementsPage.fixture.ts
- packages/cluster-ui/src/statementsTable/statementsTable.tsx
- packages/cluster-ui/src/transactionsPage/utils.ts
- packages/cluster-ui/src/util/appStats.spec.ts
- packages/cluster-ui/src/util/appStats.ts
- yarn.lock
This PR has no UI changes. It updates the code to work with the latest `crdb-protobuf-client` refactor and adds handling for new protobuf fields. The latest protobuf field is still pending merge https://github.com/cockroachdb/cockroach/pull/60791, so a `0.0.7-beta.1` version has been published in the meantime for this PR to work.
> cluster-ui: update crdb-protobuf-client

- packages/cluster-ui/src/statementDetails/statementDetails.module.scss
cluster-ui had `design-tokens` import which
wasn't installed as dependency and caused failure
during publishing.
> cluster-ui: clean up unused CSS import

- packages/cluster-ui/src/barCharts/barCharts.module.scss
- packages/cluster-ui/src/barCharts/barCharts.tsx
- packages/cluster-ui/src/statementDetails/statementDetails.tsx
- packages/cluster-ui/src/statementsPage/statementsPage.spec.tsx
- packages/cluster-ui/src/statementsPage/statementsPage.tsx
- packages/cluster-ui/src/statementsTable/statementsTable.module.scss
- packages/cluster-ui/src/statementsTable/statementsTable.tsx
- packages/cluster-ui/src/statementsTable/statementsTableContent.tsx
- packages/cluster-ui/src/transactionDetails/transactionDetails.tsx
- packages/cluster-ui/src/transactionsPage/transactionsPage.tsx
- packages/cluster-ui/src/transactionsTable/transactionsBarCharts.ts
- packages/cluster-ui/src/transactionsTable/transactionsTable.tsx
The first commit in this PR is #220, which should go in before this.
This PR addresses a lot of the nits observed in @awoods187' testing outlined in https://github.com/cockroachdb/cockroach/issues/60001.
The last two commits add contention and max disk usage information to the pages based on previously agreed on designs by @Annebirzin. Here are some visuals:
> cluster-ui: miscellaneous fixes and additions to statements/transactions page/details

- packages/storybook-ui-components/stories/Tooltip.stories.tsx
'Reasonable' spelling was corrected on the tooltip storybook
> ui-components: 'reasonable' spelling was corrected

- packages/ui-components/jest.testing.config.js
- packages/ui-components/package.json
- packages/ui-components/src/Button/Button.test.tsx
- yarn.lock
> Refractor button unit tests to use react testing library

- packages/ui-components/jest.testing.config.js
- packages/ui-components/package.json
- packages/ui-components/src/Avatar/Avatar.test.tsx
- packages/ui-components/src/Avatar/Avatar.tsx
- yarn.lock
> Refractor avatar unit tests to use react testing library

- packages/cluster-ui/src/sortedtable/sortedtable.module.scss
- packages/cluster-ui/src/sortedtable/table.module.scss
- packages/cluster-ui/src/sortedtable/tableHead/tableHead.module.scss
Execution stats tab on statement details page contains several tables
that due to some regressions had broken styles and missed border colors,
header and footer backgrounds.
Current change recovers some lost styles and fixes stylus nested style rules.
---
> cluster-ui: fix styles for execution stats tables

- packages/cluster-ui/src/barCharts/barChartFactory.tsx
- packages/cluster-ui/src/statementsTable/statementsTable.tsx
- packages/cluster-ui/src/statementsTable/statementsTableContent.tsx
- packages/cluster-ui/src/transactionsTable/transactionsTable.tsx
- packages/cluster-ui/src/util/docs.ts
This PR updates the tooltip text according to this figma design: https://www.figma.com/file/MoSPFkEyJfGipCmQvvLg1a/obsrv-query-performance?node-id=1834%3A2895
Additionally, the second commit adds an option to the bar chart to display a message of "no samples" accompanied with a tooltip when a sampled execution stat has not been sampled yet. This is more user friendly as we would previously show a zero value. This is a screenshot for the second commit:
Closes https://github.com/cockroachdb/cockroach/issues/61346
Closes https://github.com/cockroachdb/cockroach/issues/61607
> cluster-ui: update tooltips and add "no samples" tooltip on statements/transaction pages

- packages/cluster-ui/src/sessions/sessionDetails.tsx
- packages/cluster-ui/src/sessions/sessionsDetailsConnected.stories.tsx
- packages/cluster-ui/src/sessions/sessionsPage.tsx
- packages/cluster-ui/src/sessions/terminateQueryModal.tsx
- packages/cluster-ui/src/sessions/terminateSessionModal.tsx
- packages/cluster-ui/src/store/index.ts
- packages/cluster-ui/src/store/notifications/index.ts
- packages/cluster-ui/src/store/notifications/notifications.sagas.ts
- packages/cluster-ui/src/store/sagas.ts
- packages/cluster-ui/src/store/terminateQuery/terminateQuery.sagas.ts
provide separate notifications saga and expose its action, so consumer
app can build around it its own notification handlers. small cleanups.
> cluster-ui: sessions, terminate modal notifications

- packages/cluster-ui/src/sortedtable/sortedtable.module.scss
- packages/cluster-ui/src/sortedtable/table.module.scss
- packages/cluster-ui/src/sortedtable/tableHead/tableHead.module.scss
**cluster-ui 20.2 backport** for https://github.com/cockroachdb/ui/pull/241
Execution stats tab on statement details page contains several tables
that due to some regressions had broken styles and missed border colors,
header and footer backgrounds.
Current change recovers some lost styles and fixes stylus nested style rules.
> backport cluster-ui 20.2:  fix execution stats styles

- packages/cluster-ui/src/statementDetails/diagnostics/diagnosticsView.tsx
- packages/cluster-ui/src/statementDetails/statementDetails.fixture.ts
- packages/cluster-ui/src/statementDetails/statementDetails.selectors.ts
- packages/cluster-ui/src/statementDetails/statementDetails.stories.tsx
- packages/cluster-ui/src/statementDetails/statementDetails.tsx
- packages/cluster-ui/src/statementDetails/statementDetailsConnected.ts
- packages/cluster-ui/src/store/reducers.ts
- packages/cluster-ui/src/store/uiConfig/index.ts
- packages/cluster-ui/src/store/uiConfig/uiConfig.reducer.ts
Before, it wasn't necessary to customize UI components depending
on specific runtime conditions.
But now, it has to be possible to allow some client application
code to define which components have to be hidden on UI or shown.
In this particular change, "Statement diagnostics" link has to be
hidden because an entire Statement Diagnostics page might not be
available in client's code.
UI customization is implemented within redux store as separate
slice where all required customization params can be defined
with their default values.
To change some params, client's application has to dispatch
uiConfig's "update" action with partially filled configuration that
includes only params which have to be changed.
> cluster-ui: ui customization parameters

- packages/cluster-ui/src/empty/emptyPanel/emptyPanel.module.scss
- packages/cluster-ui/src/empty/emptyPanel/emptyPanel.tsx
- packages/cluster-ui/src/statementDetails/diagnostics/diagnosticsView.spec.tsx
- packages/cluster-ui/src/statementDetails/diagnostics/diagnosticsView.tsx
- packages/cluster-ui/src/statementDetails/statementDetails.spec.tsx
- packages/cluster-ui/src/statementsPage/statementsPage.tsx
Statements table and statement diagnostics table display empty state
as embedded placeholder inside of table (when table header is visible).
According to new design, empty state placeholders should replace entire
table.
Current change changes placeholders in statements table and diagnostics
tables. Also some refactoring is done in Empty panel component to reuse
components from `ui-components` package and clean up hand made styles.
Figma design: https://www.figma.com/file/C85d0mrz8dkNs7Nw5mcTmf/obsrv-statements?node-id=1143%3A2455
> cluster-ui: correct design for empty state in statements table

- packages/cluster-ui/src/anchor/anchor.module.scss
- packages/cluster-ui/src/pagination/pagination.module.scss
- packages/cluster-ui/src/pagination/pagination.tsx
- packages/cluster-ui/src/search/search.module.scss
- packages/cluster-ui/src/search/search.tsx
- packages/cluster-ui/src/sortedtable/table.module.scss
- packages/cluster-ui/src/sortedtable/tableHead/tableHead.module.scss
- packages/cluster-ui/src/sortedtable/tableHead/tableHead.tsx
- packages/cluster-ui/src/sortedtable/tableRow/tableRow.tsx
- packages/cluster-ui/src/statementDetails/diagnostics/diagnosticsView.module.scss
- packages/cluster-ui/src/statementDetails/diagnostics/diagnosticsView.tsx
- packages/cluster-ui/src/statementDetails/planView/planView.tsx
- packages/cluster-ui/src/statementDetails/statementDetails.module.scss
- packages/cluster-ui/src/statementDetails/statementDetails.tsx
- packages/cluster-ui/src/statementsPage/statementsPage.module.scss
- packages/cluster-ui/src/statementsPage/statementsPage.tsx
- packages/cluster-ui/src/summaryCard/summaryCard.module.scss
- packages/cluster-ui/src/table/table.module.scss
- packages/cluster-ui/src/table/table.tsx
Different pages use different implementations of table component
with their very own styles or override default styles with custom.
It caused styles mismatching.
Current change doesn't try to unify all components/styles but
locally fixes styles and somehow reuses it. It'll allow to
backport changes for older versions with less stress.
Before & After screens:
----
----
> cluster-ui:  fix statements page styles

- packages/cluster-ui/src/statementDetails/diagnostics/diagnosticsView.tsx
- packages/cluster-ui/src/statementDetails/statementDetails.fixture.ts
- packages/cluster-ui/src/statementDetails/statementDetails.selectors.ts
- packages/cluster-ui/src/statementDetails/statementDetails.stories.tsx
- packages/cluster-ui/src/statementDetails/statementDetails.tsx
- packages/cluster-ui/src/statementDetails/statementDetailsConnected.ts
- packages/cluster-ui/src/store/reducers.ts
- packages/cluster-ui/src/store/uiConfig/index.ts
- packages/cluster-ui/src/store/uiConfig/uiConfig.reducer.ts
Before, it wasn't necessary to customize UI components depending
on specific runtime conditions.
But now, it has to be possible to allow some client application
code to define which components have to be hidden on UI or shown.
In this particular change, "Statement diagnostics" link has to be
hidden because an entire Statement Diagnostics page might not be
available in client's code.
UI customization is implemented within redux store as separate
slice where all required customization params can be defined
with their default values.
To change some params, client's application has to dispatch
uiConfig's "update" action with partially filled configuration.
> backport 20.2: ui customization parameters

- packages/cluster-ui/src/empty/emptyPanel/emptyPanel.module.scss
- packages/cluster-ui/src/empty/emptyPanel/emptyPanel.tsx
- packages/cluster-ui/src/statementDetails/diagnostics/diagnosticsView.spec.tsx
- packages/cluster-ui/src/statementDetails/diagnostics/diagnosticsView.tsx
- packages/cluster-ui/src/statementDetails/statementDetails.spec.tsx
- packages/cluster-ui/src/statementsPage/statementsPage.tsx
Statements table and statement diagnostics table display empty state
as embedded placeholder inside of table (when table header is visible).
According to new design, empty state placeholders should replace entire
table.
Current change changes placeholders in statements table and diagnostics
tables. Also some refactoring is done in Empty panel component to reuse
components from `ui-components` package and clean up hand made styles.
(cherry picked from commit 28211df72f67b76a17c1d232b09c93935d595b7d)
> backport 20.2: correct design for empty states in statements table

- packages/cluster-ui/src/anchor/anchor.module.scss
- packages/cluster-ui/src/pagination/pagination.module.scss
- packages/cluster-ui/src/pagination/pagination.tsx
- packages/cluster-ui/src/search/search.module.scss
- packages/cluster-ui/src/search/search.tsx
- packages/cluster-ui/src/sortedtable/table.module.scss
- packages/cluster-ui/src/sortedtable/tableHead/tableHead.module.scss
- packages/cluster-ui/src/sortedtable/tableHead/tableHead.tsx
- packages/cluster-ui/src/sortedtable/tableRow/tableRow.tsx
- packages/cluster-ui/src/statementDetails/diagnostics/diagnosticsView.module.scss
- packages/cluster-ui/src/statementDetails/diagnostics/diagnosticsView.tsx
- packages/cluster-ui/src/statementDetails/planView/planView.tsx
- packages/cluster-ui/src/statementDetails/statementDetails.module.scss
- packages/cluster-ui/src/statementDetails/statementDetails.tsx
- packages/cluster-ui/src/statementsPage/statementsPage.module.scss
- packages/cluster-ui/src/summaryCard/summaryCard.module.scss
- packages/cluster-ui/src/table/table.module.scss
- packages/cluster-ui/src/table/table.tsx
Different pages use different implementations of table component
with their very own styles or override default styles with custom.
It caused styles mismatching.
Current change doesn't try to unify all components/styles but
locally fixes styles and somehow reuses it. It'll allow to
backport changes for older versions with less stress.
> backport 20.2: fix statements page styles

- packages/cluster-ui/src/store/index.ts
- packages/cluster-ui/src/store/reducers.spec.ts
- packages/cluster-ui/src/store/reducers.ts
Initially, it wasn't possible to reset redux state at some point
during application life cycle.
Switching between multiple clusters that should keep their own
state in redux store requires to have ability to re-initialize
an empty redux state.
> cluster-ui: reset redux state action

- packages/cluster-ui/src/barCharts/barCharts.tsx
- packages/cluster-ui/src/statementDetails/statementDetails.module.scss
- packages/cluster-ui/src/statementDetails/statementDetails.tsx
- packages/cluster-ui/src/statementsPage/statementsPage.module.scss
- packages/cluster-ui/src/statementsPage/statementsPage.tsx
- packages/cluster-ui/src/statementsTable/statementsTable.stories.tsx
- packages/cluster-ui/src/statementsTable/statementsTable.tsx
- packages/cluster-ui/src/statementsTable/statementsTableContent.tsx
- packages/cluster-ui/src/summaryCard/summaryCard.module.scss
- packages/cluster-ui/src/transactionDetails/transactionDetails.tsx
- packages/cluster-ui/src/transactionsPage/transactionsPage.tsx
- packages/cluster-ui/src/util/format.ts
- packages/cluster-ui/src/util/index.ts
- packages/cluster-ui/src/util/totalWorkload.fixture.ts
- packages/cluster-ui/src/util/totalWorkload.spec.ts
- packages/cluster-ui/src/util/totalWorkload.ts
Adding new column for `% of all runtime` into statements page
`% of runtime all statements with this fingerprint represent, compared to the cumulative runtime of all queries within the last hour or specified time interval.`
Issue: https://github.com/cockroachdb/cockroach/issues/61475 
This PR also fixes some ui on details page to align with the mockup (change of weights of fonts, spacing)
> packages/cluster-ui: add % of all runtime to statements

- packages/cluster-ui/src/store/index.ts
cluster-ui package has to re-export uiConfig actions to allow external apps
to change the reducers state in type-safe way - with action creator and
provided types.
> cluster-ui: re-export uiConfiguration actions

- packages/cluster-ui/src/store/index.ts
- packages/cluster-ui/src/store/reducers.spec.ts
- packages/cluster-ui/src/store/reducers.ts
Initially, it wasn't possible to reset redux state at some point
during application life cycle.
Switching between multiple clusters that should keep their own
state in redux store requires to have ability to re-initialize
an empty redux state.
(cherry picked from commit 8e52a107eb3283c4ed60cca01499a866eeb717d4)
> backport 20.2: reset redux state action

- packages/cluster-ui/src/store/index.ts
cluster-ui package has to re-export uiConfig actions to allow external apps
to change the reducers state in type-safe way - with action creator and
provided types.
> backport 20.2: re-export uiConfiguration actions

- packages/cluster-ui/src/statementDetails/statementDetails.tsx
Recently Statement details page were extended with `uiConfig` prop that
includes flags to tweak visibility for particular UI elements.
`uiConfig` prop should not be required, and it should be okay to
skip it to render default UI.
Current change adds default value for `uiConfig` prop and makes this
field as optional for statementDetailsProps type.
> cluster-ui: default values for statement details ui configuration

- packages/cluster-ui/src/empty/emptyTable/emptyTable.module.scss
- packages/cluster-ui/src/empty/emptyTable/emptyTable.tsx
- packages/cluster-ui/src/statementDetails/diagnostics/diagnosticsView.module.scss
- packages/cluster-ui/src/statementDetails/diagnostics/diagnosticsView.spec.tsx
- packages/cluster-ui/src/statementDetails/diagnostics/diagnosticsView.tsx
- packages/cluster-ui/src/statementDetails/statementDetails.spec.tsx
- packages/cluster-ui/src/statementsPage/statementsPage.tsx
Several commits ago (62a6d372a55619625ae41f0b9dc4632a82ec3cee), empty state component for Statement diagnostics view has been
changed to old design and now it is rolled back.
Additional changes were made to reuse `ui-components` (`Heading`, `Text` and `Button` components).
This change fixes issue described https://github.com/cockroachdb/ui/pull/253#issuecomment-806903656
New designs:
> cluster-ui: proper empty state design for statement diagnostics view

- packages/cluster-ui/src/statementDetails/diagnostics/diagnosticsView.tsx
- packages/cluster-ui/src/statementDetails/statementDetails.tsx
- packages/cluster-ui/src/statementDetails/statementDetailsConnected.ts
- packages/cluster-ui/src/statementsPage/statementsPage.tsx
- packages/cluster-ui/src/statementsPage/statementsPageConnected.tsx
- packages/cluster-ui/src/statementsTable/statementsTable.tsx
- packages/cluster-ui/src/statementsTable/statementsTableContent.tsx
- packages/cluster-ui/src/store/analytics/analytics.reducer.ts
- packages/cluster-ui/src/store/index.ts
- packages/cluster-ui/src/table/table.tsx
Current change extends list of tracked events and refactors
analytics reducer to make it more generic.
Analytics reducer provides single action (`track`) that accepts
different event types - it allows extend this action to work with
new types and have single to watch in case client's app is interested
in all possible analytics events.
Event types include required `name` field that has to follow Segment's
naming conventions and the rest of optional fields can be considered as
Segments properties.
To avoid coupling of analytics events with components - all logic are
defined in Connected components. Connected components have been refactored
`mapDispatchToProps` object is defined as function to be able to dispatch
multiple events in single method (`onActivateStatementDiagnostics` method …
> cluster-ui: analytics tracking events

- packages/cluster-ui/src/store/liveness/liveness.sagas.ts
- packages/cluster-ui/src/store/nodes/nodes.sagas.ts
- packages/cluster-ui/src/store/sessions/sessions.sagas.ts
- packages/cluster-ui/src/store/statementDiagnostics/statementDiagnostics.sagas.ts
- packages/cluster-ui/src/store/statements/statements.sagas.ts
- packages/cluster-ui/src/store/utils/sagaEffects/throttleWithReset.ts
Previous implementation of redux-sagas for fetching new data from server was
straightforward and didn't take into account cases such as resetting an entire
redux state, so it cause cases when request to some data is dispatched, then
redux state is reset, and after this sagas would handle returned data as
usual (which in fact causes inconsistent store state).
To avoid this cases, sagas have to be cancelled when redux state is reset
and all responses after this should be ignored. To achieve desired behavior,
most of the changes are done within custom `throttleWithReset` effect.
- now, it's behavior is changed to take and process only latest actions
instead of processing every incoming action. It guaranties that all previous
actions and forked tasks are cancelled.
- `throttleWithReset` …
> cluster-ui: cancel active sagas when redux state is reset

- packages/cluster-ui/src/store/liveness/liveness.sagas.ts
- packages/cluster-ui/src/store/nodes/nodes.sagas.ts
- packages/cluster-ui/src/store/sessions/sessions.sagas.ts
- packages/cluster-ui/src/store/statementDiagnostics/statementDiagnostics.sagas.ts
- packages/cluster-ui/src/store/statements/statements.sagas.ts
- packages/cluster-ui/src/store/utils/sagaEffects/throttleWithReset.ts
Previous implementation of redux-sagas for fetching new data from server was
straightforward and didn't take into account cases such as resetting an entire
redux state, so it cause cases when request to some data is dispatched, then
redux state is reset, and after this sagas would handle returned data as
usual (which in fact causes inconsistent store state).
To avoid this cases, sagas have to be cancelled when redux state is reset
and all responses after this should be ignored. To achieve desired behavior,
most of the changes are done within custom `throttleWithReset` effect.
- now, it's behavior is changed to take and process only latest actions
instead of processing every incoming action. It guaranties that all previous
actions and forked tasks are cancelled.
- `throttleWithReset` …
> backport 20.2: cancel active sagas when redux state is reset

- packages/cluster-ui/src/empty/emptyTable/emptyTable.module.scss
- packages/cluster-ui/src/empty/emptyTable/emptyTable.tsx
- packages/cluster-ui/src/statementDetails/diagnostics/diagnosticsView.module.scss
- packages/cluster-ui/src/statementDetails/diagnostics/diagnosticsView.spec.tsx
- packages/cluster-ui/src/statementDetails/diagnostics/diagnosticsView.tsx
- packages/cluster-ui/src/statementDetails/statementDetails.spec.tsx
- packages/cluster-ui/src/statementsPage/statementsPage.tsx
Several commits ago, empty state component for Statement diagnostics view has been
changed to old design and now it is rolled back.
Additional changes were made to reuse `ui-components` (Heading, Text and Button).
(cherry picked from commit 026949afc7468433ace4e2a9b260b91425d82d42)
> backport 20.2: proper empty state design for statement diagnostics view

- packages/cluster-ui/package.json
- packages/cluster-ui/src/api/sqlStatsApi.ts
- packages/cluster-ui/src/statementsPage/statementsPage.fixture.ts
- packages/cluster-ui/src/statementsPage/statementsPage.tsx
- packages/cluster-ui/src/statementsPage/statementsPageConnected.tsx
- packages/cluster-ui/src/store/sagas.ts
- packages/cluster-ui/src/store/sqlStats/index.ts
- packages/cluster-ui/src/store/sqlStats/sqlStats.reducer.ts
- packages/cluster-ui/src/store/sqlStats/sqlStats.sagas.spec.ts
- packages/cluster-ui/src/store/sqlStats/sqlStats.sagas.ts
- packages/cluster-ui/src/tableStatistics/tableStatistics.module.scss
- packages/cluster-ui/src/tableStatistics/tableStatistics.tsx
- packages/cluster-ui/src/transactionDetails/transactionDetails.stories.tsx
- packages/cluster-ui/src/transactionDetails/transactionDetails.tsx
- packages/cluster-ui/src/transactionsPage/transactionsPage.stories.tsx
- packages/cluster-ui/src/transactionsPage/transactionsPage.tsx
- yarn.lock
cluster-ui: add button to reset SQL stats on statement page and txn page
Addresses https://github.com/cockroachdb/cockroach/issues/33315
Before: 
Stmt page
Txn Page
After:
Stmt Page:
Txn Page:
Tooltip
> cluster-ui: add button to reset SQL stats on statement page and txn page

- packages/cluster-ui/package.json
- packages/cluster-ui/src/statementDetails/statementDetails.fixture.ts
- packages/cluster-ui/src/statementDetails/statementDetails.tsx
- packages/cluster-ui/src/statementsPage/statementsPage.fixture.ts
- packages/cluster-ui/src/util/appStats/appStats.fixture.ts
- packages/cluster-ui/src/util/appStats/appStats.spec.ts
- packages/cluster-ui/src/util/appStats/appStats.ts
- yarn.lock
cluster-ui
Adding a new field for Last execution time on Statements Details page
Dependency: https://github.com/cockroachdb/cockroach/pull/63491
Related to: https://github.com/cockroachdb/cockroach/issues/60974
> cluster-ui: last execution time for statement

- packages/cluster-ui/src/sessions/sessionDetails.tsx
- packages/cluster-ui/src/sessions/sessionDetailsConnected.tsx
- packages/cluster-ui/src/sessions/sessionsPage.fixture.ts
- packages/cluster-ui/src/sessions/sessionsPage.tsx
- packages/cluster-ui/src/sessions/sessionsPageConnected.tsx
- packages/cluster-ui/src/sessions/sessionsTable.tsx
- packages/cluster-ui/src/store/analytics/analytics.reducer.ts
expose analytics events on sessions:
- on table sorted
- on session link clicked
- on terminate session
- on terminate statement
and sessions details page:
- on back to sessions clicked
- on terminate session
- on terminate statement
> cluster-ui: sessions tracking events [backport 20.2]

- packages/cluster-ui/src/sessions/sessionDetails.tsx
- packages/cluster-ui/src/sessions/sessionDetailsConnected.tsx
- packages/cluster-ui/src/sessions/sessionsPage.fixture.ts
- packages/cluster-ui/src/sessions/sessionsPage.tsx
- packages/cluster-ui/src/sessions/sessionsPageConnected.tsx
- packages/cluster-ui/src/sessions/sessionsTable.tsx
- packages/cluster-ui/src/store/analytics/analytics.reducer.ts
expose analytics events on sessions:
- on table sorted
- on session link clicked
- on terminate session
- on terminate statement
and sessions details page:
- on back to sessions clicked
- on terminate session
- on terminate statement
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/ui/278)
> cluster-ui: sessions tracking events

- packages/ui-components/package.json
Manually publishing `@cockroachlabs/ui-components@0.2.18` after [publish failure](https://github.com/cockroachdb/ui/runs/2411506965?check_suite_focus=true)`
I don't know what's going on with the failed publishing, but this is a quick fix for now.
> Manual Publish

- packages/cluster-ui/src/statementDetails/statementDetails.fixture.ts
- packages/cluster-ui/src/statementDetails/statementDetails.tsx
- packages/cluster-ui/src/statementDetails/statementDetailsConnected.ts
- packages/cluster-ui/src/statementsPage/statementsPage.fixture.ts
- packages/cluster-ui/src/statementsPage/statementsPage.tsx
- packages/cluster-ui/src/statementsPage/statementsPageConnected.tsx
- packages/cluster-ui/src/store/nodes/nodes.selectors.ts
Returning information from cache about which region each node is on.
Part of issue https://github.com/cockroachdb/cockroach/issues/59979
Dependency for PR (handles the backend changes) https://github.com/cockroachdb/cockroach/pull/64605
This will be followed by another PR with the changes on the ui visible to the user.
> cluster-ui: return information about node regions to statement pages

- packages/cluster-ui/package.json
- packages/cluster-ui/src/barCharts/barCharts.tsx
- packages/cluster-ui/src/barCharts/genericBarChart.tsx
- packages/cluster-ui/src/barCharts/numericStatLegend.tsx
- packages/cluster-ui/src/barCharts/utils.ts
- packages/cluster-ui/src/statementDetails/statementDetails.fixture.ts
- packages/cluster-ui/src/statementDetails/statementDetails.tsx
- packages/cluster-ui/src/statementsPage/statementsPage.fixture.ts
- packages/cluster-ui/src/statementsTable/statementsTable.tsx
- packages/cluster-ui/src/transactionsTable/transactionsBarCharts.ts
- packages/cluster-ui/src/transactionsTable/transactionsTable.tsx
- packages/cluster-ui/src/transactionsTable/utils.ts
- packages/cluster-ui/src/util/appStats/appStats.fixture.ts
- packages/cluster-ui/src/util/appStats/appStats.spec.ts
- packages/cluster-ui/src/util/appStats/appStats.ts
- packages/cluster-ui/src/util/arrays.ts
- packages/cluster-ui/src/util/fixLong.ts
- packages/cluster-ui/src/util/index.ts
- packages/cluster-ui/src/util/totalWorkload.ts
- yarn.lock
Add information about which node and region a statement was executed on.
Resolves: https://github.com/cockroachdb/cockroach/issues/59979
Release note (ui change): Display on Statement Details information about
nodes and regions a statement was executed on.
> cluster-ui: adding information about node and region on statement details

- packages/cluster-ui/src/sessions/sessionsPage.tsx
- packages/cluster-ui/src/sortedtable/sortedtable.spec.tsx
- packages/cluster-ui/src/sortedtable/sortedtable.tsx
- packages/cluster-ui/src/sortedtable/tableHead/tableHead.tsx
- packages/cluster-ui/src/statementDetails/statementDetails.tsx
- packages/cluster-ui/src/statementsPage/statementsPage.spec.tsx
- packages/cluster-ui/src/statementsPage/statementsPage.tsx
- packages/cluster-ui/src/statementsTable/statementsTable.stories.tsx
- packages/cluster-ui/src/transactionDetails/transactionDetails.tsx
- packages/cluster-ui/src/transactionsPage/transactionsPage.tsx
- packages/cluster-ui/src/util/appStats/appStats.ts
- yarn.lock
Sort on tables of Statement, Transaction and Sessions page were
not using the right value from the url regarding sorting. It was
using the right sortKey, but always doing ascending. Fix done so
it uses the right value for the boolean.
Since the sortKet might be different for different users on Statement
Page (difference on columns being displayed), use the name of the
columns, instead of the key.
Fixes: https://github.com/cockroachdb/cockroach/issues/65085
Release note (bug fix): Sort on tables are now picking up the
correct value from the url.
> cluster-ui: fix sort on tables

- packages/cluster-ui/src/barCharts/utils.ts
- packages/cluster-ui/src/queryFilter/filter.module.scss
- packages/cluster-ui/src/queryFilter/filter.tsx
- packages/cluster-ui/src/sortedtable/sortedtable.module.scss
- packages/cluster-ui/src/sortedtable/sortedtable.tsx
- packages/cluster-ui/src/statementDetails/statementDetails.tsx
- packages/cluster-ui/src/statementsPage/statementsPage.tsx
- packages/cluster-ui/src/statementsTable/statementsTable.stories.tsx
- packages/cluster-ui/src/statementsTable/statementsTable.tsx
- packages/cluster-ui/src/statementsTable/statementsTableContent.module.scss
- packages/cluster-ui/src/statementsTable/statementsTableContent.tsx
- packages/cluster-ui/src/transactionDetails/transactionDetails.tsx
- packages/cluster-ui/src/transactionsPage/transactions.fixture.ts
- packages/cluster-ui/src/transactionsPage/transactionsPage.tsx
- packages/cluster-ui/src/transactionsPage/utils.spec.ts
- packages/cluster-ui/src/transactionsPage/utils.ts
- packages/cluster-ui/src/transactionsTable/transactionsTable.tsx
- packages/cluster-ui/src/util/arrays.ts
- yarn.lock
Display information about which Regions/Nodes a statement was executed and
a filter option for region and another for nodes.
Both new filters will only be displayed if there is more than one value.
**Values on the table:**
**Filter:**
**Columns selector on statement page:**
Release note (ui change): Display on Statement and Transaction pages information
about nodes and regions a statement was executed on.
> cluster-ui: adding information about node and region on stmt/transaction pages

- packages/cluster-ui/README.md
- packages/cluster-ui/package.json
Increasing the minor version of cluster-ui to represent the next
unreleased version of CRDB (21.2) that is being developed on the master
branch of `cockroachdb/cockroach`.
There was no mention of how minor versions of cluster-ui are aligned to
major release versions of CRDB, so adding a section outlining this
mapping. Also documenting the versioning skew and deprecation that
happened after the CRDB 21.1 release.
> 21.2 Version alignment

- packages/cluster-ui/babel.config.js
- packages/cluster-ui/src/core/antd.scss
- packages/cluster-ui/src/core/index.module.scss
antd style set contains a bunch of direct rules for tagnames.
this leads to style conflicts when we use cluster-ui in
managed service env. to avoid this only fast solution was
to copy antd styles in src and comment out all rules of
such type.
> cluster-ui: remove tagname css rules

- packages/cluster-ui/babel.config.js
- packages/cluster-ui/src/core/antd.scss
- packages/cluster-ui/src/core/index.module.scss
antd style set contains a bunch of direct rules for tagnames.
this leads to style conflicts when we use cluster-ui in
managed service env. to avoid this only fast solution was
to copy antd styles in src and comment out all rules of
such type.
> backport[20.2] cluster-ui: remove tagname css rules

- packages/cluster-ui/babel.config.js
- packages/cluster-ui/src/core/antd.scss
- packages/cluster-ui/src/core/index.module.scss
antd style set contains a bunch of direct rules for tagnames.
this leads to style conflicts when we use cluster-ui in
managed service env. to avoid this only fast solution was
to copy antd styles in src and comment out all rules of
such type.
> backport [21.1] cluster-ui: remove tagname css rules

- renovate.json5
@cockroachlabs/icons package depends on `@svgr/cli` package
to build icons and it works well with at most 5.3.0 version.
Other latest versions cause build failures and looks like
some incompatible change was introduced in minor versions.
Recently, we had the same issue and the version was
downgraded back to 5.3.0 in following commit 03eaecbe4ca725e93427fdfc3ae4bb2e15958a93
This change extends renovate configuration to avoid upgrading
version for @svgr/cli package.
Also this change should resolve build failures in some of existing renovate PRs
> exclude svgr/cli package from been updated by renovate

- .github/workflows/publish-ui-components.yml
`ui-component` publish action failed with error that
`@cockroachlabs/icons` package was not found. The cause
of this error was with missing build step for all
packages during publish.
This change adds build and test steps so all dependencies
are in place.
> build all packages before publish ui-components

- package.json
- packages/ui-components/package.json
- yarn.lock
This is a manual tweak of https://github.com/cockroachdb/ui/pull/413 to remove a deprecated webpack-cli switch (`--display-error-details`)
> upgrades: Upgrading webpack packages for ui-components

- packages/design-tokens/README.md
- packages/design-tokens/config.json
- packages/design-tokens/package.json
Export stylus tokens for use in db console
Motivated by https://github.com/cockroachdb/cockroach/issues/72674
> design-tokens: export stylus tokens

- packages/design-tokens/package.json
Added a prepublishOnly script to ensure that tokens are built on package
publish.
> design-tokens: Added a prepublishOnly script

- packages/ui-components/package.json
- packages/ui-components/webpack.config.js
- yarn.lock
We were experimenting with CSS-in-JS libraries when ui-components was
first created. astroturf would allow us to introduce CSS-in-JS, but
continue to use our existing CSS processing pipeline (i.e., SCSS).
However, we aren't using CSS-in-JS in any of our files, so we can
remove the dependency.
> ui-components: remove astroturf from dependencies

- packages/ui-components/src/Input/index.ts
The types in `Input/index.ts` are not exported separately to address
the below warnings.
```
WARNING in ./src/Input/index.ts 4:0-109
export 'TextInputProps' (reexported as 'TextInputProps') was not found
in './TextTypeInput' (possible exports: BaseTextInput,
MultilineTextInput, NumberInput, SingleLineTextInput)
@ ./src/index.ts 4:0-25 4:0-25
WARNING in ./src/Input/index.ts 4:0-109
export 'NumberProps' (reexported as 'NumberProps') was not found in
'./TextTypeInput' (possible exports: BaseTextInput, MultilineTextInput,
NumberInput, SingleLineTextInput)
@ ./src/index.ts 4:0-25 4:0-25
```
> ui-components: address export warnings during build

- docs/README.md
- docs/RFCs/00000000_template.md
- docs/RFCs/README.md
The frontend-focused RFC directory is a space for frontend contributors
to propose and discuss best practices that will impact multiple teams.
We've been having discussions in #frontend-learners, but slack threads
aren't ideal for coming to a consensus, especially across teams.
The frontend-focused RFC directory is not intended for consumer-facing
features. Those RFCs should be added to `docs/RFCS` in the relevant
repository.
> docs: add directory for frontend-focused RFCs

- packages/eslint-config/index.js
- packages/ui-components/src/Input/Field.tsx
We have been adding stricter rules to the eslint config in the
managed-service repo. Now that the eslint version has been updated, we
can update the rules as well.
There was one naming rule violation in the ui-components package that
is now ignored because the we are passing a component in as a prop. The
casing is correct.
I moved everything below https://github.com/cockroachlabs/managed-service/blob/master/console/.eslintrc.json#L6.
> eslint-config, ui-components: add stricter rules to eslint config

- packages/design-tokens/tokens/color/core.json
This PR adds a series of colors that are defined in our internal
branding documents. Currently, they're not under the standard format of
`ColorBase<Name><number>` as I felt that naming them under the
design-system format caused a lot of headaches in going back and forth
deciding colors.
These tokens are intended to be used in things like Graphics, and more
visual use cases. Naming them by the color name is intended to speed up
visual work by not needing to reference an external hex + branding doc
using the `tokens.js` file. I'm not super tied to it, and if we'd rather
have the same number naming under a "brand" nest I'd be happy with that
as well.
Some of these tokens are duplicates, of existing design system ones
above. Some of them are new to the `ui` repository. The final exported …
> design-tokens: add color tokens with branding names

- .github/workflows/deploy-storybook.yml
- .github/workflows/publish-ui-components.yml
- .github/workflows/pull-request-ci.yml
- package.json
- packages/icons/package.json
- packages/storybook-ui-components/package.json
- packages/ui-components/package.json
- yarn.lock
This PR upgrades Lerna in the workspace to version 5.30. It also upgrade the github workflows to use Node version 16 (rather than the extinct Node 12) since checks were failing due to an incompatibility with Node 12 and Lerna 5+.
> Upgrade Lerna to version 5.3.0

- packages/ui-components/src/Badge/Badge.tsx
Added a boolean prop to Badge that when set to true will render the value of props to a `<pre>` tag inside the Badge.
**What I'm really doing is making a change to a component to test the automated publishing flow
<details>
<br />
```bash
npm install @cockroachlabs/ui-components@0.3.12-canary.482.53981b4.0
yarn add @cockroachlabs/ui-components@0.3.12-canary.482.53981b4.0
```
</details>
> UI Components: Added `debug` prop to Badge

- .github/CODEOWNERS
- .github/workflows/pull-request-ci.yml
- .github/workflows/release.yml
- packages/icons/AUTHORS
- packages/icons/notests.js
- packages/icons/package.json
- packages/storybook-ui-components/AUTHORS
- packages/ui-components/AUTHORS
- yarn.lock
Some things I've been meaning to get around to,
😢 Dropping Rachel Wang from the `/docs` reviewers list (and removing my comment)
🧹  Removing some unnecessary dev dependencies from icons package
📜 Removing AUTHORS files (because of inconsistent use)
🔩 Only run release workflow on push to master, or pull_request
🔩 Skip release workflow if pull request is from a fork 🍴
> Various clean up tasks

- packages/ui-components/src/Tooltip/Tooltip.tsx
The timeout from the Tooltip component was causing the component to stick for longer than it should.
This commit removes the timeout, until a better solution is made.
Part Of https://cockroachlabs.atlassian.net/browse/CC-6325
Before
https://www.loom.com/share/3f645bba0419429f9b92d946d0538e54
After
https://www.loom.com/share/3ec548eb22624cd8b0fe543cc7d3d7b1
> [CC-6325]ui-components: remove timeout from tooltip

- packages/ui-components/src/InlineAlert/InlineAlert.tsx
The intent prop (of type InlineAlertIntent) was being passed directly to
the Icon component's fill prop (of type IconFill). InlineAlertIntent is
compatible as a subset of IconFill (which is a union of IconIntent and
some string types), but are clearly different types and not
interchangable.
The fix is to cast the InlineAlertIntent to a string and then pass the
string cast as an IconFill.
<details>
<br />
```bash
npm install @cockroachlabs/ui-components@0.4.2-canary.499.3859477258.0
yarn add @cockroachlabs/ui-components@0.4.2-canary.499.3859477258.0
```
</details>
> ui-components: Fixing type compatibility in InlineAlerts

- packages/ui-components/src/InlineAlert/InlineAlert.module.scss
This commit fixes the alignment of the icon
on the inlineAlert component.
Before
After
Epic: None
> ui: fix icon alignment on inline alert

- .github/workflows/release.yml
- package.json
Releasing seems pretty stable, so we can reduce the noise in the logs
> Remove `-v` from release command

- packages/storybook-ui-components/stories/Icon.stories.tsx
- packages/ui-components/src/Icon/Icon.module.scss
- packages/ui-components/src/Icon/Icon.tsx
Adding icons sizes to cover uses in Cockroach Cloud console.
<details>
<br />
```bash
npm install @cockroachlabs/ui-components@0.6.3-canary.509.4388278210.0
yarn add @cockroachlabs/ui-components@0.6.3-canary.509.4388278210.0
```
</details>
> ui-components: Updating icon sizes

- packages/ui-components/src/Icon/Icon.module.scss
Having a default `margin` is causing far more trouble than it's worth. Something with the way that CSS modules are composed, doesn't allow internal Icon styles to be overridden easily. We're better off having implementors add their own margins.
<details>
<br />
```bash
npm install @cockroachlabs/ui-components@0.6.5-canary.513.4493441166.0
yarn add @cockroachlabs/ui-components@0.6.5-canary.513.4493441166.0
```
</details>
> ui-components: Remove margin from Icon

- packages/storybook-ui-components/.storybook/preview.ts
- packages/storybook-ui-components/stories/Icon.stories.tsx
@cockroachlabs/ui-components now extracts it's dependency styles (making it easier to override component styles) requiring the consuming app to include dependency styles. Including the `dist/main.css` in Storybook Preview as well as accounting for icons that no longer have `margin: auto` by default.
> storybook: Update to account for ui-components extracted CSS

- packages/design-tokens/tokens/color/core.json
Introduces a few new color tokens to the design system for use in Onboarding on Cockroach Cloud. Also introduces a teal used for highlighting text and icons.
<details>
<br />
```bash
npm install @cockroachlabs/design-tokens@0.4.12-canary.520.5126452973.0
npm install @cockroachlabs/ui-components@0.7.2-canary.520.5126452973.0
yarn add @cockroachlabs/design-tokens@0.4.12-canary.520.5126452973.0
yarn add @cockroachlabs/ui-components@0.7.2-canary.520.5126452973.0
```
</details>
> tokens: introduce blue-gray tokens to design system

- packages/storybook-ui-components/.babelrc.json
- packages/storybook-ui-components/.storybook/main.js
- packages/storybook-ui-components/package.json
- packages/storybook-ui-components/stories/ExpandableText.stories.tsx
- packages/storybook-ui-components/stories/Tooltip.stories.tsx
- packages/ui-components/package.json
- packages/ui-components/webpack.config.js
- yarn.lock
The "knobs" addon is basically deprecated in favor of the built-in "Controls" addon [1]. That's enabled here, but only configured for <Tooltip/> for now.
[1] https://storybook.js.org/docs/react/essentials/controls
closes #517
> storybook: upgrade to v7

- .github/workflows/release.yml
- package.json
- packages/icons/package.json
- packages/icons/src/index.ts
- packages/icons/svg/preserveFill/italy.svg
- packages/ui-components/package.json
- packages/ui-components/src/Icon/Flag.tsx
- pnpm-lock.yaml
Bumping the version to release new flag additions.
<details>
<br />
```bash
npm install @cockroachlabs/icons@0.7.13-canary.548.8653412450.0
npm install @cockroachlabs/ui-components@0.7.14-canary.548.8653412450.0
yarn add @cockroachlabs/icons@0.7.13-canary.548.8653412450.0
yarn add @cockroachlabs/ui-components@0.7.14-canary.548.8653412450.0
```
</details>
> ui-components, icons: bump package version
